#------
# cosine similarity
#--------
cosine.similarity <- function(x, y){
  (x %*% y) / sqrt(x%*%x * y%*%y)
}
tmp <- data.frame(t(feaImp.long))
cosine.lt.vs.ALL <- data.frame(
  f.40 = c(cosine.similarity(tmp$female.lt.40, tmp$female.ALL.ALL)),
  f.45 = c(cosine.similarity(tmp$female.lt.45, tmp$female.ALL.ALL)),
  f.50 = c(cosine.similarity(tmp$female.lt.50, tmp$female.ALL.ALL)),
  f.55 = c(cosine.similarity(tmp$female.lt.55, tmp$female.ALL.ALL)),
  f.60 = c(cosine.similarity(tmp$female.lt.60, tmp$female.ALL.ALL)),
  f.65 = c(cosine.similarity(tmp$female.lt.65, tmp$female.ALL.ALL)),
  f.70 = c(cosine.similarity(tmp$female.lt.70, tmp$female.ALL.ALL)),
  f.75 = c(cosine.similarity(tmp$female.lt.75, tmp$female.ALL.ALL)),
  f.80 = c(cosine.similarity(tmp$female.lt.80, tmp$female.ALL.ALL)),
  f.bt.55.70 = c(cosine.similarity(tmp$female.bt.55, tmp$female.ALL.ALL)),
  m.40 = c(cosine.similarity(tmp$male.lt.40, tmp$male.ALL.ALL)),
  m.45 = c(cosine.similarity(tmp$male.lt.45, tmp$male.ALL.ALL)),
  m.50 = c(cosine.similarity(tmp$male.lt.50, tmp$male.ALL.ALL)),
  m.55 = c(cosine.similarity(tmp$male.lt.55, tmp$male.ALL.ALL)),
  m.60 = c(cosine.similarity(tmp$male.lt.60, tmp$male.ALL.ALL)),
  m.65 = c(cosine.similarity(tmp$male.lt.65, tmp$male.ALL.ALL)),
  m.70 = c(cosine.similarity(tmp$male.lt.70, tmp$male.ALL.ALL)),
  m.75 = c(cosine.similarity(tmp$male.lt.75, tmp$male.ALL.ALL)),
  m.80 = c(cosine.similarity(tmp$male.lt.80, tmp$male.ALL.ALL)),
  m.bt.55.70 = c(cosine.similarity(tmp$male.bt.55, tmp$male.ALL.ALL))
)
row.names(cosine.lt.vs.ALL) <- "cosine.lt.vs.ALL"
cosine.lt.vs.gt <- data.frame(
  f.40 = c(cosine.similarity(tmp$female.lt.40, tmp$female.gt.40)),
  f.45 = c(cosine.similarity(tmp$female.lt.45, tmp$female.gt.45)),
  f.50 = c(cosine.similarity(tmp$female.lt.50, tmp$female.gt.50)),
  f.55 = c(cosine.similarity(tmp$female.lt.55, tmp$female.gt.55)),
  f.60 = c(cosine.similarity(tmp$female.lt.60, tmp$female.gt.60)),
  f.65 = c(cosine.similarity(tmp$female.lt.65, tmp$female.gt.65)),
  f.70 = c(cosine.similarity(tmp$female.lt.70, tmp$female.gt.70)),
  f.75 = c(cosine.similarity(tmp$female.lt.75, tmp$female.gt.75)),
  f.80 = c(cosine.similarity(tmp$female.lt.80, tmp$female.gt.80)),
  f.bt.55.70 = c(cosine.similarity(tmp$female.bt.55, tmp$female.ALL.ALL)),
  m.40 = c(cosine.similarity(tmp$male.lt.40, tmp$male.gt.40)),
  m.45 = c(cosine.similarity(tmp$male.lt.45, tmp$male.gt.45)),
  m.50 = c(cosine.similarity(tmp$male.lt.50, tmp$male.gt.50)),
  m.55 = c(cosine.similarity(tmp$male.lt.55, tmp$male.gt.55)),
  m.60 = c(cosine.similarity(tmp$male.lt.60, tmp$male.gt.60)),
  m.65 = c(cosine.similarity(tmp$male.lt.65, tmp$male.gt.65)),
  m.70 = c(cosine.similarity(tmp$male.lt.70, tmp$male.gt.70)),
  m.75 = c(cosine.similarity(tmp$male.lt.75, tmp$male.gt.75)),
  m.80 = c(cosine.similarity(tmp$male.lt.80, tmp$male.gt.80)),
  m.bt.55.70 = c(cosine.similarity(tmp$male.bt.55, tmp$male.ALL.ALL))
)
row.names(cosine.lt.vs.gt) <- "cosine.lt.vs.gt"
cosine.gt.vs.ALL <- data.frame(
  f.40 = c(cosine.similarity(tmp$female.gt.40, tmp$female.ALL.ALL)),
  f.45 = c(cosine.similarity(tmp$female.gt.45, tmp$female.ALL.ALL)),
  f.50 = c(cosine.similarity(tmp$female.gt.50, tmp$female.ALL.ALL)),
  f.55 = c(cosine.similarity(tmp$female.gt.55, tmp$female.ALL.ALL)),
  f.60 = c(cosine.similarity(tmp$female.gt.60, tmp$female.ALL.ALL)),
  f.65 = c(cosine.similarity(tmp$female.gt.65, tmp$female.ALL.ALL)),
  f.70 = c(cosine.similarity(tmp$female.gt.70, tmp$female.ALL.ALL)),
  f.75 = c(cosine.similarity(tmp$female.gt.75, tmp$female.ALL.ALL)),
  f.80 = c(cosine.similarity(tmp$female.gt.80, tmp$female.ALL.ALL)),
  f.bt.55.70 = c(cosine.similarity(tmp$female.bt.55, tmp$female.ALL.ALL)),
  m.40 = c(cosine.similarity(tmp$male.gt.40, tmp$male.ALL.ALL)),
  m.45 = c(cosine.similarity(tmp$male.gt.45, tmp$male.ALL.ALL)),
  m.50 = c(cosine.similarity(tmp$male.gt.50, tmp$male.ALL.ALL)),
  m.55 = c(cosine.similarity(tmp$male.gt.55, tmp$male.ALL.ALL)),
  m.60 = c(cosine.similarity(tmp$male.gt.60, tmp$male.ALL.ALL)),
  m.65 = c(cosine.similarity(tmp$male.gt.65, tmp$male.ALL.ALL)),
  m.70 = c(cosine.similarity(tmp$male.gt.70, tmp$male.ALL.ALL)),
  m.75 = c(cosine.similarity(tmp$male.gt.75, tmp$male.ALL.ALL)),
  m.80 = c(cosine.similarity(tmp$male.gt.80, tmp$male.ALL.ALL)),
  m.bt.55.70 = c(cosine.similarity(tmp$male.bt.55, tmp$male.ALL.ALL))
)
row.names(cosine.gt.vs.ALL) <- "cosine.gt.vs.ALL"
cosine <- rbind(cosine.lt.vs.ALL, cosine.lt.vs.gt, cosine.gt.vs.ALL)
openxlsx::write.xlsx(cosine, "cosine.similarity.xlsx", row.names = TRUE)
#-----
# cosine similarity per model
#----
feaimp.model.long <- readxl::read_excel("~/Clare-Clustering/figuresCode/latest_figuresData.xlsx", 
                                        sheet = "feaimp.long_model_based_cosine")
feaimp.model.long <- data.frame(feaimp.model.long, row.names = 1)
feaimp.model.long <- data.frame(t(feaimp.model.long))
cosine.lt.vs.ALL <- data.frame(
  f.40.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.45.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.50.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.55.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.60.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.65.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.75.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.80.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  m.40.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.40.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.45.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.45.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.50.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.50.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.55.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.55.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.60.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.60.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.65.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.65.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.70.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.75.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.75.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.80.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.80.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.GLM, feaimp.model.long$MALE.ALL.GLM)),
  
  f.40.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.45.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.50.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.55.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.60.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.65.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.75.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.80.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.RF, feaimp.model.long$FEMALE.ALL.RF)),
  m.40.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.40.RF, feaimp.model.long$MALE.ALL.RF)),
  m.45.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.45.RF, feaimp.model.long$MALE.ALL.RF)),
  m.50.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.50.RF, feaimp.model.long$MALE.ALL.RF)),
  m.55.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.55.RF, feaimp.model.long$MALE.ALL.RF)),
  m.60.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.60.RF, feaimp.model.long$MALE.ALL.RF)),
  m.65.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.65.RF, feaimp.model.long$MALE.ALL.RF)),
  m.70.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.70.RF, feaimp.model.long$MALE.ALL.RF)),
  m.75.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.75.RF, feaimp.model.long$MALE.ALL.RF)),
  m.80.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.80.RF, feaimp.model.long$MALE.ALL.RF)),
  m.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.RF, feaimp.model.long$MALE.ALL.RF)),
  
  f.40.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.45.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.50.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.55.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.60.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.65.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.75.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.80.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  m.40.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.40.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.45.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.45.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.50.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.50.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.55.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.55.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.60.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.60.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.65.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.65.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.70.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.75.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.75.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.80.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.80.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.XGB, feaimp.model.long$MALE.ALL.XGB))
)
row.names(cosine.lt.vs.ALL) <- "cosine.lt.vs.ALL"

cosine.lt.vs.gt <- data.frame(
  f.40.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.GLM, feaimp.model.long$FEMALE.gt.40.GLM)),
  f.45.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.GLM, feaimp.model.long$FEMALE.gt.45.GLM)),
  f.50.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.GLM, feaimp.model.long$FEMALE.gt.50.GLM)),
  f.55.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.GLM, feaimp.model.long$FEMALE.gt.55.GLM)),
  f.60.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.GLM, feaimp.model.long$FEMALE.gt.60.GLM)),
  f.65.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.GLM, feaimp.model.long$FEMALE.gt.65.GLM)),
  f.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.GLM, feaimp.model.long$FEMALE.gt.70.GLM)),
  f.75.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.GLM, feaimp.model.long$FEMALE.gt.75.GLM)),
  f.80.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.GLM, feaimp.model.long$FEMALE.gt.80.GLM)),
  f.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.GLM, feaimp.model.long$FEMALE.bt55.70.GLM)),
  m.40.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.40.GLM, feaimp.model.long$MALE.gt.40.GLM)),
  m.45.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.45.GLM, feaimp.model.long$MALE.gt.45.GLM)),
  m.50.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.50.GLM, feaimp.model.long$MALE.gt.50.GLM)),
  m.55.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.55.GLM, feaimp.model.long$MALE.gt.55.GLM)),
  m.60.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.60.GLM, feaimp.model.long$MALE.gt.60.GLM)),
  m.65.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.65.GLM, feaimp.model.long$MALE.gt.65.GLM)),
  m.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.70.GLM, feaimp.model.long$MALE.gt.70.GLM)),
  m.75.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.75.GLM, feaimp.model.long$MALE.gt.75.GLM)),
  m.80.GLM = c(cosine.similarity(feaimp.model.long$MALE.lt.80.GLM, feaimp.model.long$MALE.gt.80.GLM)),
  m.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.GLM, feaimp.model.long$MALE.bt55.70.GLM)),
  
  f.40.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.RF, feaimp.model.long$FEMALE.gt.40.RF)),
  f.45.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.RF, feaimp.model.long$FEMALE.gt.45.RF)),
  f.50.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.RF, feaimp.model.long$FEMALE.gt.50.RF)),
  f.55.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.RF, feaimp.model.long$FEMALE.gt.55.RF)),
  f.60.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.RF, feaimp.model.long$FEMALE.gt.60.RF)),
  f.65.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.RF, feaimp.model.long$FEMALE.gt.65.RF)),
  f.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.RF, feaimp.model.long$FEMALE.gt.70.RF)),
  f.75.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.RF, feaimp.model.long$FEMALE.gt.75.RF)),
  f.80.RF = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.RF, feaimp.model.long$FEMALE.gt.80.RF)),
  f.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.RF, feaimp.model.long$FEMALE.bt55.70.RF)),
  m.40.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.40.RF, feaimp.model.long$MALE.gt.40.RF)),
  m.45.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.45.RF, feaimp.model.long$MALE.gt.45.RF)),
  m.50.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.50.RF, feaimp.model.long$MALE.gt.50.RF)),
  m.55.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.55.RF, feaimp.model.long$MALE.gt.55.RF)),
  m.60.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.60.RF, feaimp.model.long$MALE.gt.60.RF)),
  m.65.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.65.RF, feaimp.model.long$MALE.gt.65.RF)),
  m.70.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.70.RF, feaimp.model.long$MALE.gt.70.RF)),
  m.75.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.75.RF, feaimp.model.long$MALE.gt.75.RF)),
  m.80.RF = c(cosine.similarity(feaimp.model.long$MALE.lt.80.RF, feaimp.model.long$MALE.gt.80.RF)),
  m.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.RF, feaimp.model.long$MALE.bt55.70.RF)),
  
  f.40.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.40.XGB, feaimp.model.long$FEMALE.gt.40.XGB)),
  f.45.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.45.XGB, feaimp.model.long$FEMALE.gt.45.XGB)),
  f.50.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.50.XGB, feaimp.model.long$FEMALE.gt.50.XGB)),
  f.55.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.55.XGB, feaimp.model.long$FEMALE.gt.55.XGB)),
  f.60.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.60.XGB, feaimp.model.long$FEMALE.gt.60.XGB)),
  f.65.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.65.XGB, feaimp.model.long$FEMALE.gt.65.XGB)),
  f.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.70.XGB, feaimp.model.long$FEMALE.gt.70.XGB)),
  f.75.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.75.XGB, feaimp.model.long$FEMALE.gt.75.XGB)),
  f.80.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.lt.80.XGB, feaimp.model.long$FEMALE.gt.80.XGB)),
  f.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.XGB, feaimp.model.long$FEMALE.bt55.70.XGB)),
  m.40.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.40.XGB, feaimp.model.long$MALE.gt.40.XGB)),
  m.45.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.45.XGB, feaimp.model.long$MALE.gt.45.XGB)),
  m.50.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.50.XGB, feaimp.model.long$MALE.gt.50.XGB)),
  m.55.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.55.XGB, feaimp.model.long$MALE.gt.55.XGB)),
  m.60.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.60.XGB, feaimp.model.long$MALE.gt.60.XGB)),
  m.65.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.65.XGB, feaimp.model.long$MALE.gt.65.XGB)),
  m.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.70.XGB, feaimp.model.long$MALE.gt.70.XGB)),
  m.75.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.75.XGB, feaimp.model.long$MALE.gt.75.XGB)),
  m.80.XGB = c(cosine.similarity(feaimp.model.long$MALE.lt.80.XGB, feaimp.model.long$MALE.gt.80.XGB)),
  m.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.XGB, feaimp.model.long$MALE.bt55.70.XGB))
)
row.names(cosine.lt.vs.gt) <- "cosine.lt.vs.gt"

cosine.gt.vs.ALL <- data.frame(
  f.40.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.40.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.45.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.45.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.50.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.50.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.55.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.55.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.60.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.60.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.65.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.65.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.70.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.75.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.75.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.80.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.gt.80.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  f.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.GLM, feaimp.model.long$FEMALE.ALL.GLM)),
  m.40.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.40.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.45.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.45.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.50.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.50.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.55.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.55.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.60.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.60.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.65.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.65.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.70.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.75.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.75.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.80.GLM = c(cosine.similarity(feaimp.model.long$MALE.gt.80.GLM, feaimp.model.long$MALE.ALL.GLM)),
  m.bt.55.70.GLM = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.GLM, feaimp.model.long$MALE.ALL.GLM)),
  
  f.40.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.40.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.45.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.45.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.50.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.50.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.55.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.55.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.60.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.60.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.65.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.65.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.70.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.75.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.75.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.80.RF = c(cosine.similarity(feaimp.model.long$FEMALE.gt.80.RF, feaimp.model.long$FEMALE.ALL.RF)),
  f.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.RF, feaimp.model.long$FEMALE.ALL.RF)),
  m.40.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.40.RF, feaimp.model.long$MALE.ALL.RF)),
  m.45.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.45.RF, feaimp.model.long$MALE.ALL.RF)),
  m.50.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.50.RF, feaimp.model.long$MALE.ALL.RF)),
  m.55.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.55.RF, feaimp.model.long$MALE.ALL.RF)),
  m.60.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.60.RF, feaimp.model.long$MALE.ALL.RF)),
  m.65.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.65.RF, feaimp.model.long$MALE.ALL.RF)),
  m.70.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.70.RF, feaimp.model.long$MALE.ALL.RF)),
  m.75.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.75.RF, feaimp.model.long$MALE.ALL.RF)),
  m.80.RF = c(cosine.similarity(feaimp.model.long$MALE.gt.80.RF, feaimp.model.long$MALE.ALL.RF)),
  m.bt.55.70.RF = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.RF, feaimp.model.long$MALE.ALL.RF)),
  
  f.40.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.40.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.45.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.45.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.50.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.50.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.55.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.55.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.60.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.60.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.65.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.65.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.70.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.75.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.75.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.80.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.gt.80.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  f.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$FEMALE.bt55.70.XGB, feaimp.model.long$FEMALE.ALL.XGB)),
  m.40.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.40.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.45.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.45.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.50.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.50.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.55.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.55.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.60.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.60.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.65.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.65.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.70.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.75.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.75.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.80.XGB = c(cosine.similarity(feaimp.model.long$MALE.gt.80.XGB, feaimp.model.long$MALE.ALL.XGB)),
  m.bt.55.70.XGB = c(cosine.similarity(feaimp.model.long$MALE.bt55.70.XGB, feaimp.model.long$MALE.ALL.XGB))
)
row.names(cosine.gt.vs.ALL) <- "cosine.gt.vs.ALL"
cosine <- rbind(cosine.lt.vs.ALL, cosine.lt.vs.gt, cosine.gt.vs.ALL)
openxlsx::write.xlsx(cosine, "cosine.similarity.model.based.xlsx", row.names = TRUE)
